namespace KaloriUygulama.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<KaloriUygulama.Data.KaloriUygulamaDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(KaloriUygulama.Data.KaloriUygulamaDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.
            if (!context.Kullanicilar.Any())
            {
                context.Kullanicilar.Add(new Entities.Kullanici
                {
                    Ad = "admin",
                    Soyad = "admin",
                    Eposta = "admin",
                    Parola = "admin",
                    SifreIpucu = "admin"
                });
            }

            if (!context.Kategoriler.Any())
            {

                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Mezeler" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Çorbalar" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Ana Yemekler" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Yan Öğünler" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Ekmekler ve Unlu Mamuller" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Salatalar ve Salata Sosları" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Soslar ve Çeşniler" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Tatlılar" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Aperatifler" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "İçecekler" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Kahvaltı" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Öğle Yemeği" });
                context.Kategoriler.Add(new Entities.Kategori { KategoriAd = "Diğer" });
            }

            if (!context.Porsiyonlar.Any())
            {
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Gram" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Adet" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Adet (Küçük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Adet (Orta)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Adet (Büyük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Su Bardağı (200ml)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Kupa (Küçük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Kupa (Orta)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Kupa (Büyük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Kutu" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Parça (Küçük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Parça (Orta)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Parça (Büyük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Paket" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Top" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Dilim" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Dilim (İnce)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Dilim (Orta)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Dilim (Kalın)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Porsiyon (Küçük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Porsiyon (Orta)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Porsiyon (Büyük)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Çorba Kaşığı" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Çorba Kaşığı (Tepeleme)" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Tatlı Kaşığı" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Kase" });
                context.Porsiyonlar.Add(new Entities.Porsiyon { PorsiyonAd = "Tabak" });
            }

            if (!context.Besinler.Any())
            {
                context.Besinler.Add(new Entities.Besin { BesinAd = "Fava", Gram = 130m, Kalori = 147m, Karbonhidrat = 8.8m, Protein = 7.2m, Yag = 9m, KategoriId = 1, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "fava.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Fava", Gram = 20m, Kalori = 23m, Karbonhidrat = 1.4m, Protein = 1.1m, Yag = 1.4m, KategoriId = 1, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "fava.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Fava", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.1m, Protein = 0.1m, Yag = 0.1m, KategoriId = 1, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "fava.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mercimek Köftesi", Gram = 225m, Kalori = 291m, Karbonhidrat = 38.1m, Protein = 9.1m, Yag = 10.2m, KategoriId = 1, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekKöftesi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mercimek Köftesi", Gram = 30m, Kalori = 39m, Karbonhidrat = 5.1m, Protein = 1.2m, Yag = 1.4m, KategoriId = 1, PorsiyonId = 4, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekKöftesi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mercimek Köftesi", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.2m, Protein = 0, Yag = 0, KategoriId = 1, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekKöftesi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Paçanga Böreği", Gram = 136m, Kalori = 504m, Karbonhidrat = 17.9m, Protein = 14.8m, Yag = 42.6m, KategoriId = 1, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "Pacanga.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Paçanga Böreği", Gram = 1m, Kalori = 4m, Karbonhidrat = 0.1m, Protein = 0.1m, Yag = 0.3m, KategoriId = 1, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "Pacanga.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Tarhana Çorbası", Gram = 200m, Kalori = 121m, Karbonhidrat = 10m, Protein = 4.6m, Yag = 6.6m, KategoriId = 2, PorsiyonId = 26, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tarhana.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Tarhana Çorbası", Gram = 10m, Kalori = 6m, Karbonhidrat = 0.5m, Protein = 0.2m, Yag = 0.3m, KategoriId = 2, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tarhana.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Tarhana Çorbası", Gram = 250m, Kalori = 151m, Karbonhidrat = 12.5m, Protein = 5.7m, Yag = 8.2m, KategoriId = 2, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tarhana.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İşkembe Çorbası", Gram = 150m, Kalori = 209m, Karbonhidrat = 7.4m, Protein = 22.7m, Yag = 9.5m, KategoriId = 2, PorsiyonId = 26, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskembe.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İşkembe Çorbası", Gram = 1, Kalori = 1, Karbonhidrat = 0m, Protein = 0.2m, Yag = 0.1m, KategoriId = 2, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskembe.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mercimek Çorbası", Gram = 300m, Kalori = 137m, Karbonhidrat = 24.8m, Protein = 7.4m, Yag = 0.6m, KategoriId = 2, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekCorbasi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mercimek Çorbası", Gram = 200m, Kalori = 91m, Karbonhidrat = 16.6m, Protein = 4.9m, Yag = 0.4m, KategoriId = 2, PorsiyonId = 26, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekCorbasi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mercimek Çorbası", Gram = 1m, Kalori = 0.46m, Karbonhidrat = 0.1m, Protein = 0m, Yag = 0m, KategoriId = 2, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekCorbasi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İskender Kebap", Gram = 500m, Kalori = 755m, Karbonhidrat = 77.7m, Protein = 48.3m, Yag = 26.8m, KategoriId = 3, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskender.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İskender Kebap", Gram = 700m, Kalori = 1057m, Karbonhidrat = 108.8m, Protein = 67.6m, Yag = 37.5m, KategoriId = 3, PorsiyonId = 22, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskender.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İskender Kebap", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.2m, Protein = 0.1m, Yag = 0.1m, KategoriId = 3, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskender.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ali Nazik", Gram = 417m, Kalori = 407m, Karbonhidrat = 9.5m, Protein = 32.6m, Yag = 25.8m, KategoriId = 3, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "alinazik.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ali Nazik", Gram = 250m, Kalori = 247m, Karbonhidrat = 5.7m, Protein = 19.6m, Yag = 15.5m, KategoriId = 3, PorsiyonId = 4, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "alinazik.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ali Nazik", Gram = 1m, Kalori = 0.98m, Karbonhidrat = 0m, Protein = 0.1m, Yag = 0.1m, KategoriId = 3, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "alinazik.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Lazanya", Gram = 272m, Kalori = 494m, Karbonhidrat = 45.4m, Protein = 21.1m, Yag = 24.6m, KategoriId = 3, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "lazanya.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Lazanya", Gram = 150m, Kalori = 272m, Karbonhidrat = 25m, Protein = 11.6m, Yag = 13.6m, KategoriId = 3, PorsiyonId = 19, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "lazanya.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Lazanya", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.2m, Protein = 0.1m, Yag = 0.1m, KategoriId = 3, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "lazanya.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kısır", Gram = 110m, Kalori = 178m, Karbonhidrat = 31.7m, Protein = 4.6m, Yag = 3.8m, KategoriId = 4, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kısır.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kısır", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.3m, Protein = 0m, Yag = 0m, KategoriId = 4, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kısır.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kısır", Gram = 15m, Kalori = 24m, Karbonhidrat = 4.3m, Protein = 0.6m, Yag = 0.5m, KategoriId = 4, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kısır.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Zeytinyağlı Yaprak Sarma", Gram = 33m, Kalori = 32m, Karbonhidrat = 5.9m, Protein = 1.1m, Yag = 0.4m, KategoriId = 4, PorsiyonId = 2, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sarma.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Zeytinyağlı Yaprak Sarma", Gram = 130m, Kalori = 125m, Karbonhidrat = 23.2m, Protein = 4.4m, Yag = 1.7m, KategoriId = 4, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sarma.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Zeytinyağlı Yaprak Sarma", Gram = 20m, Kalori = 19m, Karbonhidrat = 3.6m, Protein = 0.7m, Yag = 0.3m, KategoriId = 4, PorsiyonId = 3, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sarma.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Humus", Gram = 140m, Kalori = 339m, Karbonhidrat = 18.9m, Protein = 8.2m, Yag = 24.9m, KategoriId = 4, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "humus.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Humus", Gram = 15m, Kalori = 36m, Karbonhidrat = 2.0m, Protein = 0.9m, Yag = 2.7m, KategoriId = 4, PorsiyonId = 24, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "humus.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Humus", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.1m, Protein = 0.1m, Yag = 0.2m, KategoriId = 4, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "humus.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ekmek", Gram = 25m, Kalori = 64m, Karbonhidrat = 13.2m, Protein = 2m, Yag = 0.2m, KategoriId = 5, PorsiyonId = 17, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ekmek.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ekmek", Gram = 40m, Kalori = 102m, Karbonhidrat = 21.1m, Protein = 3.2m, Yag = 0.4m, KategoriId = 5, PorsiyonId = 18, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ekmek.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ekmek", Gram = 50m, Kalori = 128m, Karbonhidrat = 26.4m, Protein = 4m, Yag = 0.4m, KategoriId = 5, PorsiyonId = 19, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ekmek.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Peynirli Poğaça", Gram = 70m, Kalori = 274m, Karbonhidrat = 21.4m, Protein = 6.1m, Yag = 18.3m, KategoriId = 5, PorsiyonId = 2, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "peynirliPogaca.jpeg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Peynirli Poğaça", Gram = 1m, Kalori = 4m, Karbonhidrat = 0.3m, Protein = 0.1m, Yag = 0.3m, KategoriId = 5, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "peynirliPogaca.jpeg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Cevizli Ekmek", Gram = 30m, Kalori = 149m, Karbonhidrat = 17.5m, Protein = 4.1m, Yag = 6.9m, KategoriId = 5, PorsiyonId = 18, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cevizliekmek.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Cevizli Ekmek", Gram = 15m, Kalori = 74m, Karbonhidrat = 8.7m, Protein = 2m, Yag = 3.5m, KategoriId = 5, PorsiyonId = 17, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cevizliekmek.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Cevizli Ekmek", Gram = 1m, Kalori = 5m, Karbonhidrat = 0.6m, Protein = 0.1m, Yag = 0.2m, KategoriId = 5, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cevizliekmek.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Rus Salatası", Gram = 56m, Kalori = 61m, Karbonhidrat = 5.61m, Protein = 1.30m, Yag = 3.84m, KategoriId = 6, PorsiyonId = 24, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "russalatasi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Rus Salatası", Gram = 45m, Kalori = 49m, Karbonhidrat = 4.49m, Protein = 1.04m, Yag = 3.08m, KategoriId = 6, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "russalatasi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Rus Salatası", Gram = 232m, Kalori = 255m, Karbonhidrat = 23.14m, Protein = 5.36m, Yag = 15.86m, KategoriId = 6, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "russalatasi.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Pırasalı Salata", Gram = 140m, Kalori = 66m, Karbonhidrat = 5.67m, Protein = 2.04m, Yag = 3.48m, KategoriId = 6, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "pirasalisalata.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Pırasalı Salata", Gram = 20m, Kalori = 9m, Karbonhidrat = 0.61m, Protein = 0.30m, Yag = 0.84m, KategoriId = 6, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "pirasalisalata.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Pırasalı Salata", Gram = 100m, Kalori = 40m, Karbonhidrat = 4.05m, Protein = 1.45m, Yag = 2.84m, KategoriId = 6, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "pirasalisalata.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sezar Salata", Gram = 30m, Kalori = 37m, Karbonhidrat = 2.61m, Protein = 4.30m, Yag = 1.14m, KategoriId = 6, PorsiyonId = 24, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sezarsalata.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sezar Salata", Gram = 365m, Kalori = 465m, Karbonhidrat = 24.61m, Protein = 48.30m, Yag = 18.24m, KategoriId = 6, PorsiyonId = 20, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sezarsalata.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sezar Salata", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.61m, Protein = 0.30m, Yag = 0.84m, KategoriId = 6, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sezarsalata.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Limon Sos", Gram = 7m, Kalori = 6m, Karbonhidrat = 0.94m, Protein = 0.30m, Yag = 0.07m, KategoriId = 7, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "limonsos.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Limon Sos", Gram = 52m, Kalori = 46m, Karbonhidrat = 13.34m, Protein = 1.33m, Yag = 0.09m, KategoriId = 7, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "limonsos.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Limon Sos", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.13m, Protein = 0.01m, Yag = 0.01m, KategoriId = 7, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "limonsos.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Çikolata Sos", Gram = 10m, Kalori = 28m, Karbonhidrat = 6.02m, Protein = 0.30m, Yag = 0.32m, KategoriId = 7, PorsiyonId = 25, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cikolatasos.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Çikolata Sos", Gram = 90m, Kalori = 252m, Karbonhidrat = 54.18m, Protein = 2.30m, Yag = 2.88m, KategoriId = 7, PorsiyonId = 14, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cikolatasos.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Çikolata Sos", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.60m, Protein = 0.30m, Yag = 0.03m, KategoriId = 7, PorsiyonId = 25, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cikolatasos.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Beyaz Sosu", Gram = 60m, Kalori = 30m, Karbonhidrat = 1.81m, Protein = 0.50m, Yag = 2.32m, KategoriId = 7, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "beyazsosu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Beyaz Sosu", Gram = 15m, Kalori = 7m, Karbonhidrat = 0.42m, Protein = 0.13m, Yag = 0.58m, KategoriId = 7, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "beyazsosu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Beyaz Sosu", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.02m, Protein = 0.01m, Yag = 0.04m, KategoriId = 7, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "beyazsosu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Baklava", Gram = 40m, Kalori = 164m, Karbonhidrat = 19.72m, Protein = 3.09m, Yag = 8.89m, KategoriId = 8, PorsiyonId = 18, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "baklava.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Baklava", Gram = 40m, Kalori = 164m, Karbonhidrat = 19.72m, Protein = 3.09m, Yag = 8.89m, KategoriId = 8, PorsiyonId = 4, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "baklava.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Baklava", Gram = 160m, Kalori = 658, Karbonhidrat = 79.97m, Protein = 34.30m, Yag = 34.78m, KategoriId = 8, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "baklava.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sütlaç", Gram = 250m, Kalori = 263m, Karbonhidrat = 53.95m, Protein = 4.46m, Yag = 3.41m, KategoriId = 8, PorsiyonId = 26, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sutlac.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sütlaç", Gram = 20m, Kalori = 21m, Karbonhidrat = 4.95m, Protein = 0.46m, Yag = 0.41m, KategoriId = 8, PorsiyonId = 25, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sutlac.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sütlaç", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.95m, Protein = 0.46m, Yag = 0.01m, KategoriId = 8, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sutlac.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Tiramisu", Gram = 100m, Kalori = 223m, Karbonhidrat = 32.95m, Protein = 5.46m, Yag = 6.41m, KategoriId = 8, PorsiyonId = 17, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tiramisu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Tiramisu", Gram = 175m, Kalori = 390m, Karbonhidrat = 57.95m, Protein = 9.46m, Yag = 11.41m, KategoriId = 8, PorsiyonId = 19, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tiramisu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Tiramisu", Gram = 130m, Kalori = 290m, Karbonhidrat = 42.95m, Protein = 6.86m, Yag = 8.41m, KategoriId = 8, PorsiyonId = 18, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tiramisu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ülker Çokoprens Atıştırmalık", Gram = 73m, Kalori = 112m, Karbonhidrat = 13.95m, Protein = 0.96m, Yag = 5.91m, KategoriId = 9, PorsiyonId = 14, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cokoprens.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ülker Çokoprens Atıştırmalık", Gram = 4m, Kalori = 6m, Karbonhidrat = 0.75m, Protein = 0.05m, Yag = 0.41m, KategoriId = 9, PorsiyonId = 2, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cokoprens.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ülker Çokoprens Atıştırmalık", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.19m, Protein = 0.01m, Yag = 0.8m, KategoriId = 9, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cokoprens.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ton Balıklı Kanepe", Gram = 210m, Kalori = 648m, Karbonhidrat = 27.6m, Protein = 12.46m, Yag = 54.41m, KategoriId = 9, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tonbaliklikanepe.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ton Balıklı Kanepe", Gram = 20m, Kalori = 61m, Karbonhidrat = 2.64m, Protein = 1.46m, Yag = 5.41m, KategoriId = 9, PorsiyonId = 2, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tonbaliklikanepe.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ton Balıklı Kanepe", Gram = 1m, Kalori = 3m, Karbonhidrat = 0.13m, Protein = 0.6m, Yag = 0.41m, KategoriId = 9, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tonbaliklikanepe.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kinoa Kraker", Gram = 32m, Kalori = 104m, Karbonhidrat = 6.95m, Protein = 4.86m, Yag = 7.41m, KategoriId = 9, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kinoakraker.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kinoa Kraker", Gram = 32m, Kalori = 104m, Karbonhidrat = 6.95m, Protein = 4.86m, Yag = 7.41m, KategoriId = 9, PorsiyonId = 18, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kinoakraker.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kinoa Kraker", Gram = 1m, Kalori = 3m, Karbonhidrat = 0.95m, Protein = 0.16m, Yag = 0.21m, KategoriId = 9, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kinoakraker.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ayran", Gram = 200m, Kalori = 100m, Karbonhidrat = 9.15m, Protein = 4.16m, Yag = 5.00m, KategoriId = 10, PorsiyonId = 6, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ayran.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ayran", Gram = 200m, Kalori = 100m, Karbonhidrat = 9.15m, Protein = 4.16m, Yag = 5.00m, KategoriId = 10, PorsiyonId = 10, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ayran.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Ayran", Gram = 350m, Kalori = 175m, Karbonhidrat = 16.95m, Protein = 7.86m, Yag = 8.71m, KategoriId = 10, PorsiyonId = 9, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ayran.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Portakal Suyu", Gram = 200m, Kalori = 120m, Karbonhidrat = 29.15m, Protein = 0.86m, Yag = 0.33m, KategoriId = 10, PorsiyonId = 6, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakalsuyu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Portakal Suyu", Gram = 100m, Kalori = 60m, Karbonhidrat = 14.15m, Protein = 0.46m, Yag = 0.17m, KategoriId = 10, PorsiyonId = 7, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakalsuyu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Portakal Suyu", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.15m, Protein = 0.00m, Yag = 0.00m, KategoriId = 10, PorsiyonId = 6, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakalsuyu.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Şalgam Suyu", Gram = 50m, Kalori = 13m, Karbonhidrat = 2.33m, Protein = 0.46m, Yag = 0.11m, KategoriId = 10, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "salgam.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Şalgam Suyu", Gram = 150m, Kalori = 39m, Karbonhidrat = 6.99m, Protein = 1.86m, Yag = 0.33m, KategoriId = 10, PorsiyonId = 2, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "salgam.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Şalgam Suyu", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.05m, Protein = 0.01m, Yag = 0.0m, KategoriId = 10, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "salgam.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kaşarlı Tost", Gram = 70m, Kalori = 211m, Karbonhidrat = 23.55m, Protein = 9.46m, Yag = 9.33m, KategoriId = 11, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kasarlitost.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kaşarlı Tost", Gram = 70m, Kalori = 211m, Karbonhidrat = 23.55m, Protein = 9.46m, Yag = 9.33m, KategoriId = 11, PorsiyonId = 3, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kasarlitost.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kaşarlı Tost", Gram = 1m, Kalori = 3m, Karbonhidrat = 0.35m, Protein = 0.16m, Yag = 0.13m, KategoriId = 11, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kasarlitost.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sucuklu Yumurta", Gram = 131m, Kalori = 317m, Karbonhidrat = 4.45m, Protein = 17.46m, Yag = 25.33m, KategoriId = 11, PorsiyonId = 20, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sucukluyumurta.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sucuklu Yumurta", Gram = 100m, Kalori = 241m, Karbonhidrat = 3.35m, Protein = 13.46m, Yag = 19.33m, KategoriId = 11, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sucukluyumurta.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Sucuklu Yumurta", Gram = 50m, Kalori = 120m, Karbonhidrat = 1.65m, Protein = 6.76m, Yag = 9.73m, KategoriId = 11, PorsiyonId = 11, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sucukluyumurta.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İncir Reçeli", Gram = 10m, Kalori = 9m, Karbonhidrat = 2.35m, Protein = 0.6m, Yag = 0.23m, KategoriId = 11, PorsiyonId = 25, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "incirreceli.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İncir Reçeli", Gram = 15m, Kalori = 14m, Karbonhidrat = 3.55m, Protein = 0.08m, Yag = 0.34m, KategoriId = 11, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "incirreceli.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "İncir Reçeli", Gram = 225m, Kalori = 220m, Karbonhidrat = 53.55m, Protein = 1.46m, Yag = 0.53m, KategoriId = 11, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "incirreceli.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Karnıyarık", Gram = 180m, Kalori = 99m, Karbonhidrat = 4.55m, Protein = 5.79m, Yag = 6.33m, KategoriId = 12, PorsiyonId = 20, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "karniyarik.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Karnıyarık", Gram = 345m, Kalori = 191m, Karbonhidrat = 8.75m, Protein = 11.86m, Yag = 12.33m, KategoriId = 12, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "karniyarik.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Karnıyarık", Gram = 10m, Kalori = 5m, Karbonhidrat = 0.25m, Protein = 0.36m, Yag = 0.36m, KategoriId = 12, PorsiyonId = 22, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "karniyarik.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Hamsili Pilav", Gram = 234m, Kalori = 334m, Karbonhidrat = 30.15m, Protein = 26.25m, Yag = 12.23m, KategoriId = 12, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "hamsilipilav.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Hamsili Pilav", Gram = 300m, Kalori = 436m, Karbonhidrat = 39.52m, Protein = 34.55m, Yag = 16.03m, KategoriId = 12, PorsiyonId = 22, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "hamsilipilav.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Hamsili Pilav", Gram = 15m, Kalori = 21m, Karbonhidrat = 1.98m, Protein = 1.76m, Yag = 0.83m, KategoriId = 12, PorsiyonId = 24, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "hamsilipilav.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mantı", Gram = 300m, Kalori = 508m, Karbonhidrat = 89.15m, Protein = 12.36m, Yag = 10.33m, KategoriId = 12, PorsiyonId = 27, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "manti.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mantı", Gram = 10m, Kalori = 16m, Karbonhidrat = 2.95m, Protein = 0.46m, Yag = 0.35m, KategoriId = 12, PorsiyonId = 23, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "manti.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Mantı", Gram = 190m, Kalori = 322m, Karbonhidrat = 56.15m, Protein = 7.86m, Yag = 6.53m, KategoriId = 12, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "manti.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Portakal", Gram = 100m, Kalori = 46m, Karbonhidrat = 11.55m, Protein = 0.86m, Yag = 0.33m, KategoriId = 13, PorsiyonId = 25, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakal.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Portakal", Gram = 220m, Kalori = 101m, Karbonhidrat = 25.55m, Protein = 1.76m, Yag = 0.46m, KategoriId = 13, PorsiyonId = 25, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakal.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Portakal", Gram = 300m, Kalori = 138m, Karbonhidrat = 34.55m, Protein = 2.46m, Yag = 0.63m, KategoriId = 13, PorsiyonId = 25, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakal.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kuru Yemiş", Gram = 40m, Kalori = 204m, Karbonhidrat = 14.05m, Protein = 6.36m, Yag = 13.0m, KategoriId = 13, PorsiyonId = 24, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kuruyemis.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kuru Yemiş", Gram = 100m, Kalori = 512m, Karbonhidrat = 35.55m, Protein = 15.86m, Yag = 32.50m, KategoriId = 13, PorsiyonId = 26, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kuruyemis.jpgı" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Kuru Yemiş", Gram = 1m, Kalori = 5m, Karbonhidrat = 0.55m, Protein = 0.33m, Yag = 0.43m, KategoriId = 13, PorsiyonId = 1, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kuruyemis.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Yeşil Kahve", Gram = 25m, Kalori = 10m, Karbonhidrat = 2.55m, Protein = 1.33m, Yag = 1.43m, KategoriId = 13, PorsiyonId = 21, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "yesilkahve.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Yeşil Kahve", Gram = 1m, Kalori = 5m, Karbonhidrat = 1.5m, Protein = 0.33m, Yag = 0.53m, KategoriId = 13, PorsiyonId = 18, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "yesilkahve.jpg" });
                context.Besinler.Add(new Entities.Besin { BesinAd = "Yeşil Kahve", Gram = 1m, Kalori = 4m, Karbonhidrat = 0.5m, Protein = 0.20m, Yag = 0.23m, KategoriId = 13, PorsiyonId = 18, BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "yesilkahve.jpg" });
            }
        }
    }
}
